[package]
name = "axstarry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["monolithic"]

monolithic = ["arceos_api/monolithic", "axfeat/monolithic", "paging", "fs", "net", "multitask", "irq", "signal", "axnet/ip"]

img = ["axruntime/img"]

# Multicore
smp = ["axfeat/smp", "spinlock/smp"]


# Floating point/SIMD
fp_simd = ["axfeat/fp_simd"]

# Interrupts
irq = ["arceos_api/irq", "axfeat/irq"]

# Memory
alloc = ["arceos_api/alloc", "axfeat/alloc", "axio/alloc"]
alloc-tlsf = ["axfeat/alloc-tlsf"]
alloc-slab = ["axfeat/alloc-slab"]
alloc-buddy = ["axfeat/alloc-buddy"]
paging = ["axfeat/paging"]
tls = ["axfeat/tls"]

# Multi-threading and scheduler
multitask = ["arceos_api/multitask", "axfeat/multitask"]
sched_fifo = ["axfeat/sched_fifo"]
sched_rr = ["axfeat/sched_rr"]
sched_cfs = ["axfeat/sched_cfs"]

# Display
display = ["arceos_api/display", "axfeat/display"]

# Fs
fs = ["axruntime/fs", "arceos_api/fs"]

# Networking
net = ["arceos_api/net", "axfeat/net"]
dns = []

# Signal
signal = ["axruntime/signal"]

# Logging
log-level-off = ["axfeat/log-level-off"]
log-level-error = ["axfeat/log-level-error"]
log-level-warn = ["axfeat/log-level-warn"]
log-level-info = ["axfeat/log-level-info"]
log-level-debug = ["axfeat/log-level-debug"]
log-level-trace = ["axfeat/log-level-trace"]


[dependencies]
numeric-enum-macro = { git = "https://github.com/mexus/numeric-enum-macro" }
crate_interface = { path = "../../crates/crate_interface" }
axfeat = { path = "../../api/axfeat" }
arceos_api = { path = "../../api/arceos_api" }
axruntime = { path = "../../modules/axruntime" }
axconfig = { path = "../../modules/axconfig" }
axlog = { path = "../../modules/axlog" }
axio = { path = "../../crates/axio" }
axerrno = { path = "../../crates/axerrno" }
axhal = { path = "../../modules/axhal" }
axalloc = { path = "../../modules/axalloc", optional = true }
axtask = { path = "../../modules/axtask" }
axsync = { path = "../../modules/axsync" }
axfs = { path = "../../modules/axfs" }
axnet = { path = "../../modules/axnet" }
axprocess = { path = "../../modules/axprocess" }
axmem = { path = "../../modules/axmem" } 
lazy_init = { path = "../../crates/lazy_init" }
spinlock = { path = "../../crates/spinlock" }
kernel_guard = { path = "../../crates/kernel_guard" }
axsignal = { path = "../../modules/axsignal" }
riscv = "0.10"
bitflags = "2.0"
num_enum = { version = "0.5.11", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }