[package]
name = "syscall_entry"
version = "0.1.0"
edition = "2021"

authors = ["Youjie Zheng <zyj578335934@gmail.com>"]
description = "ArceOS user program library for linux apps with posix_syscall"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["monolithic"]

monolithic = ["arceos_api/monolithic", "axfeat/monolithic", "paging", "fs", "multitask", "irq", "signal"]

img = ["axruntime/img"]

# Multicore
smp = ["axfeat/smp", "spinlock/smp"]


# Floating point/SIMD
fp_simd = ["axfeat/fp_simd"]

# Interrupts
irq = ["arceos_api/irq", "axfeat/irq"]

# Memory
paging = ["axfeat/paging"]
tls = ["axfeat/tls"]

# Multi-threading and scheduler
multitask = ["arceos_api/multitask", "axfeat/multitask"]
sched_fifo = ["axfeat/sched_fifo"]
sched_rr = ["axfeat/sched_rr"]
sched_cfs = ["axfeat/sched_cfs"]

# Display
display = ["arceos_api/display", "axfeat/display"]

# Fs
fs = ["axruntime/fs", "arceos_api/fs"]

# Signal
signal = ["axruntime/signal"]

# Logging
log-level-off = ["axfeat/log-level-off"]
log-level-error = ["axfeat/log-level-error"]
log-level-warn = ["axfeat/log-level-warn"]
log-level-info = ["axfeat/log-level-info"]
log-level-debug = ["axfeat/log-level-debug"]
log-level-trace = ["axfeat/log-level-trace"]

# Syscall Select
syscall_net = ["syscall_net/net"]
# 只有当 syscall_mem 和 syscall_fs 同时启动时，才会启动 syscall_mem/fs
syscall_fs = ["dep:syscall_fs", "syscall_mem?/fs", "fs"]
syscall_mem = ["dep:syscall_mem"]

[dependencies]
numeric-enum-macro = { git = "https://github.com/mexus/numeric-enum-macro" }
crate_interface = { path = "../../../crates/crate_interface" }
axfeat = { path = "../../../api/axfeat" }
arceos_api = { path = "../../../api/arceos_api" }
axruntime = { path = "../../../modules/axruntime" }
axconfig = { path = "../../../modules/axconfig" }
axlog = { path = "../../../modules/axlog" }
axerrno = { path = "../../../crates/axerrno" }
axhal = { path = "../../../modules/axhal" }
axtask = { path = "../../../modules/axtask" }
axsync = { path = "../../../modules/axsync" }
axfs = { path = "../../../modules/axfs" }
axprocess = { path = "../../../modules/axprocess" }
lazy_init = { path = "../../../crates/lazy_init" }
spinlock = { path = "../../../crates/spinlock" }
kernel_guard = { path = "../../../crates/kernel_guard" }
axsignal = { path = "../../../modules/axsignal" }
riscv = "0.10"
bitflags = "2.0"
num_enum = { version = "0.5.11", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
syscall_utils = { path = "../syscall_utils" }
syscall_fs = { path = "../syscall_fs", optional = true }
syscall_net = { path = "../syscall_net", optional = true }
syscall_mem = { path = "../syscall_mem", optional = true }